config/routes.rb
Ajaxdemo::Application.routes.draw do
  resources :projects do
    collection do
      get 'ajaxaction'
    end
  end

  root :to => 'projects#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
	
  attr_accessible :name
  validates :name, :presence => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
      format.js
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
      format.js
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new
    # render :js => "alert('Hello Rails!');"
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
      format.js
    end
    # render :inline => "hiii its inline"
    # head :bad_request
    # head :created, :location => new_project_path

  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
      format.js
    end
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
        # format.js
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])
    
    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    @projects = Project.all
    respond_to do |format|
      format.html { redirect_to projects_path , notice: 'Project was successfully deleted.' }
      format.json { head :no_content }
      format.js
    end
  end

  def ajaxaction
    # render :text => "alert('hello')"
    # respond_to do |format|
    #   format.js{ render action: "alert" }
    # end
    # render :nothing => true
    # render "ajaxaction"
    # render :ajaxaction
    # render :action => "ajaxaction"
    # render :text => "ok"
    render :js => "alert('Hello Rails!');"
 end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ajaxdemo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/_edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project , :remote => true %> |
<%= link_to 'Back', projects_path, :remote => true %>

app/views/projects/_form.html.erb
<%= form_for(@project, :remote => true) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_index.html.erb
<div id="projects">
<h1 >Listing projects</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= link_to project.name , project , :remote => true %></td>
    <!-- <td><%#= link_to 'Show',  %></td> -->
    <td><%= link_to 'Edit', edit_project_path(project) , :remote => true %></td>
    <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' },  :remote => true %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_project_path, :remote => true  %>
<%= link_to  'click' , ajaxaction_projects_path, :remote => true  %>
</div>

app/views/projects/_new.html.erb
<div id="new_project">

<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path , :remote => true %>
</div>

app/views/projects/_show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @project.name %>
</p>


<%= link_to 'Edit', edit_project_path(@project), :remote => true %> |
<%= link_to 'Back', projects_path , :remote => true %>

app/views/projects/ajaxaction.js.erb
alert("Hello ,AJAX!");

app/views/projects/destroy.js.erb
$('#projects').html("<%= j( render(:partial => 'index')) %>");

app/views/projects/edit.html.erb
<%= render 'edit' %>

app/views/projects/edit.js.erb
$('#projects').html("<%= j( render(:partial => 'edit')) %>");

app/views/projects/index.html.erb
<%= render 'index' %>

app/views/projects/new.html.erb
<!-- <h1>New project</h1> -->

<%= render 'new' %>

<%#= link_to 'Back', projects_path %>

app/views/projects/new.js.erb
$('#projects').html("<%= escape_javascript( render(:partial => 'new')) %>");

app/views/projects/show.html.erb
<%= render 'show' %>

app/views/projects/show.js.erb
$('#projects').html("<%= j( render(:partial => 'show')) %>");